services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - survey-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PG_USER=${PG_USER}
      - PG_HOST=db
      - PG_DATABASE=${PG_DATABASE}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=5432
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - survey-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - survey-network

volumes:
  pgdata:

networks:
  survey-network:
    driver: bridge