CREATE TABLE IF NOT EXISTS survey_responses (
                                                response_id UUID PRIMARY KEY,
                                                lifestyle TEXT,
                                                q2_choice TEXT,
                                                q2a_influence TEXT,
                                                q2aa_frequent TEXT,
                                                q2b_payment TEXT,
                                                q2b_affect TEXT,
                                                q3_payment_option TEXT,
                                                q4_payment_influence TEXT,
                                                q5_flex_fare TEXT,
                                                q5a_try_again TEXT,
                                                q5aa_fairness TEXT,
                                                q6_show_up_hope TEXT,
                                                q6a_take_chance TEXT,
                                                q6aa_reaction TEXT,
                                                q7_courtesy_impact TEXT,
                                                q8_coupon_choice TEXT,
                                                q9_weather TEXT,
                                                q10_likelihood TEXT,
                                                q11_family_preference TEXT,
                                                q12_age_group TEXT,
                                                location TEXT
);